# Generated by Django 4.1 on 2022-08-23 22:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "cities"},
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
        ),
        migrations.AlterField(
            model_name="letter",
            name="content",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="letter",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date published"
            ),
        ),
    ]
